[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CH-FREE#1
PublicKey = kLP1kA+BuzvA6ecozP0c82I8u1aXkZmfMCxBZEqpNHY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.6.181:51820
PersistentKeepalive = 25