[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = gJj9dboQe7D/RnKupcnw3AizSvLq08PIVDs71gTx3Uo=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA-FREE#18
PublicKey = TrotkXhPfmF2QA4hi+QOtPiCCUZzYhq8lNv0svSYMGg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.47.234.226:51820
PersistentKeepalive = 25