[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA-FREE#1
PublicKey = 4+452KKZ/BpmTeJ0Ua5YulgtVJKrFlw0AKKo4PtlYxM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 178.249.214.65:51820
PersistentKeepalive = 25