[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = AJEPS66Y92Vi90EQNHSh4kLTPGqYLv/7CbBQKRKJGkY=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# CA-FREE#15
PublicKey = q7jFh12kfVdVqAEdLxugYLf2+JNCT2HdCJDFbpEIg2c=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.238.156.194:51820
PersistentKeepalive = 25