[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = SH+xJrPi7x2Wk0JlJvGbEqP/YqxPvePbwaU6OYFB5kI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#1
PublicKey = agoivyLoPqor8MxA/s6UWJSMcA2pMl+ajO3vy/q3oWQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.125.235.18:51820
PersistentKeepalive = 25