[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 6KlDFsDeUMNuNROYgmiKMCTkCbYthu0rwKolgsEsHGU=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# JP-FREE#8
PublicKey = /sWD2USgF+NjIqfoLjjnt13s84p9FKKRxl4MRxeoyRo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 212.102.51.241:51820
PersistentKeepalive = 25