[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#1
PublicKey = x5qWLikynaMDbB2UrQAqsLNjd7+jGvneBvbMQ6M0mSQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.14.26.127:51820
PersistentKeepalive = 25