[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#8
PublicKey = eOxxZFIwEjujPtVOmN8JcgpmtKikl7O5qM9Oe1hUqmc=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.47:51820
PersistentKeepalive = 25