[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#13
PublicKey = rf3F9avKpfKKe+m6RA6y3PJyF4IU9KKkv8tYGcAziDE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.44:51820
PersistentKeepalive = 25