[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#35
PublicKey = jDrSMRMm6XJgYGcSd01QqJbYiW13dyaOKp8GWDs0rTQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.177.125.172:51820
PersistentKeepalive = 25