[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#43
PublicKey = lqxGpBwoRUrxKpUvlq3VhJ9SCHgt8N5KxcGEfuz+Vys=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 169.150.196.71:51820
PersistentKeepalive = 25