[Interface]
PrivateKey = YOUR_PRIVATE_KEY_BASE64
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#1
PublicKey = vH2i8RY1qc66XfqwrixBpvH4K9GYJatkugJj0GHgoUQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 217.23.3.76:51820
PersistentKeepalive = 25